spring:
  web:
    locale: en_US
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 15
  application:
    name: safehub-api
  datasource:
    url: jdbc:postgresql://localhost:5432/safehub
    username: manuelloverso
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration